### ISSUE TITLE
[BUG] Unable to run the unihtml docker image on my M2 Mac

### ISSUE THREAD

**Issue by kishankishore2908** [unidoc/unihtml#10]
## Description
I am unable to run the `unihtml` docker image on my M2 Mac

## Expected Behavior
The docker container should start without any errors.

## Actual Behavior
1. Run `docker run --platform linux/arm64 -p 8080:8080 -e UNIDOC_METERED_API_KEY=key unidoccloud/unihtml` on the terminal on a M2 pro.

## Attachments
```
docker run --platform linux/arm64 -p 8080:8080 -e UNIDOC_METERED_API_KEY=key unidoccloud/unihtml
Unable to find image 'unidoccloud/unihtml:latest' locally
latest: Pulling from unidoccloud/unihtml
Digest: sha256:085784309a8223f90eeb8d2d4e10db0c47ed832da9ff4298ee7c38534763cb65
Status: Image is up to date for unidoccloud/unihtml:latest
docker: image with reference docker.io/unidoccloud/unihtml:latest was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64.
See 'docker run --help'.
```

**Comment by 3ace** [comment]
hi @kishankishore2908 you should change the platform to `linux/amd64` instead of `linux/1rm64` for it to work.

**Comment by ahall** [comment]
Feel free to try it now @kishankishore2908, we build for amd64 and arm64 now.
